server:
  port: 15000
dubbo:
  application:
    name: wemedia-service
  protocol:
    port: 20885
  registry:
    address: nacos://43.143.209.196:8848?username=nacos&password=nacos
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews-task?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 200339LHT
  redis:
    host: 123.57.165.115
    port: 8567
    password: 123321
xxl:
  job:
    admin:
      address: http://123.57.165.115:7171/xxl-job-admin
    executor:
      appname: xxl-job-executor-ShiXun
      port: 9999
    accessToken: default_token