spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews-wemedia?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 200339LHT
  rabbitmq:
    host: 123.57.165.115
    port: 5672
    virtual-host: shiXun
    username: temp
    password: 123321
server:
  port: 14000
minio:
  accessKey: minio
  secretKey: minio123
  bucket: shixun
  endpoint: http://123.57.165.115:9000
  readPath: http://123.57.165.115:9000
tess4j:
  data-path: E:\work_project
  language: chi_sim
#  dubbo 消费端配置
dubbo:
  application:
    name: article-service
  registry:
    address: nacos://43.143.209.196:8848?username=nacos&password=nacos
  protocol:
    port: 20881
