
spring:
  profiles:
    active: dev
  redis:
    host: 123.57.165.115
    port: 8567
    password: 123321

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 200339LHT
server:
  port: 12000