
spring:
  application:
    name: News-app-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        - id: user-service
          uri: http://localhost:12000
          predicates:
            - Path=/user/**
          filters:
            # 跳过一个路径前缀
            - StripPrefix=1
        - id: article-service
          uri: http://localhost:13000
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix=1
server:
  port: 21300
